BackEndVentR/BackEndVentR/PresentacionVentR/Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PresentacionVentR.EnvioDato;
using PresentacionVentR.Models;

namespace PresentacionVentR.Controllers
{
    public class ProductoController : Controller
    {
       private ApiProducto apiProducto = new ApiProducto();
        private EnvioDatoProveedor apiProveedor = new EnvioDatoProveedor();
        // GET: ProductoController


        public async Task<ActionResult> ProductoProveedorView()
        {

            var respuesta = await apiProveedor.listarPersonaAsync();

            return View(respuesta);
        }
        [HttpPost]
        public async Task<ActionResult> Buscar(string IdProveedor)
        {
            HttpContext.Session.SetString("IdProveedor", IdProveedor);
            var respuesta = await apiProducto.listarProductoPorProveedor(Convert.ToInt32(IdProveedor));
            return View("Index",respuesta);
        }

        public async Task<IActionResult> DesactivarProducto(int idProducto)
        {

            if (await apiProducto.DesactivarProducto(idProducto))
            {
                return View("Index", await apiProducto.listarProductoPorProveedor(
                    Convert.ToInt32(HttpContext.Session.GetString("IdProveedor"))));
            }

            return View("Error", new ErrorViewModel { RequestId = "3" });

        }

        public async Task<IActionResult> Index() {
            return View("Index", await apiProducto.listarProductoPorProveedor(
        Convert.ToInt32(HttpContext.Session.GetString("IdProveedor"))));
        }

        public async Task<IActionResult> ActivarProducto(int idProducto)
        {

            if (await apiProducto.ActivarProducto(idProducto))
            {
                return View("Index", await apiProducto.listarProductoPorProveedor(
                    Convert.ToInt32(HttpContext.Session.GetString("IdProveedor"))));
            }

            return View("Error", new ErrorViewModel { RequestId = "3" });


        }

        // GET: ProductoController/Details/5
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            Producto respuesta = await apiProducto.filtrandoProductoAsync(id);
            return View(respuesta);
        }






    }
}

BackEndVentR/BackEndVentR/PresentacionVentR/Controllers/ProveedorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PresentacionVentR.EnvioDato;
using PresentacionVentR.Models;

namespace PresentacionVentR.Controllers
{
    public class ProveedorController : Controller
    {
        [HttpGet]
        public async Task<IActionResult> ListarProveedores()
        {
            EnvioDatoProveedor envioDatoProveedor = new EnvioDatoProveedor();

            var respuesta = await envioDatoProveedor.listarPersonaAsync();

            return View(respuesta);
        }

        public ActionResult RegistrarProveedor()
        {
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> Registrar([FromBody]  Proveedor proveedor)
        {
            EnvioDatoProveedor envioDatoProveedor = new EnvioDatoProveedor();
      
           bool respuesta = await envioDatoProveedor.registrarProveedorAsync(proveedor);

            return Json(respuesta);
        }

        [HttpGet]
        public async Task<IActionResult> FiltrarProveedor(int idProveedor)
        {
            EnvioDatoProveedor envioDatoProveedor = new EnvioDatoProveedor();
            Proveedor respuesta = await envioDatoProveedor.filtrandoProveedorAsync(idProveedor);

            return View(respuesta);
        }
        [HttpGet]
        public async Task<IActionResult> DetalleProveedor(int idProveedor)
        {
            EnvioDatoProveedor envioDatoProveedor = new EnvioDatoProveedor();
            Proveedor respuesta = await envioDatoProveedor.filtrandoProveedorAsync(idProveedor);

            return View(respuesta);
        }


        [HttpPut]
        public async Task<JsonResult> Modificar([FromBody] Proveedor proveedor)
        {
            EnvioDatoProveedor envioDatoProveedor = new EnvioDatoProveedor();

            bool respuesta = await envioDatoProveedor.modificarProveedorAsync(proveedor);

            return Json(respuesta);
        }


        public async Task<IActionResult> EliminarProveedor(int idProveedor)
        {
            EnvioDatoProveedor envioDatoProveedor = new EnvioDatoProveedor();
            bool respuesta = await envioDatoProveedor.eliminarProveedorAsync(idProveedor);

            return Json(respuesta);
            //return View("ListarProveedores", await envioDatoProveedor.listarPersonaAsync());
        }



        [HttpGet]
        public async Task<IActionResult> ActivarProveedor(int IdProveedor)
        {
            EnvioDatoProveedor envioDatoProveedor = new EnvioDatoProveedor();
            bool respuesta = await envioDatoProveedor.activarProveedorAsync(IdProveedor);
            return Json(respuesta);
        }
        [HttpGet]
        public async Task<IActionResult> DesactivarProveedor(int IdProveedor)
        {
            EnvioDatoProveedor envioDatoProveedor = new EnvioDatoProveedor();
            bool respuesta = await envioDatoProveedor.desactivarProveedorAsync(IdProveedor);
            return Json(respuesta);
        }

    }
}

BackEndVentR/BackEndVentR/PresentacionVentR/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PresentacionVentR.EnvioDato;
using PresentacionVentR.Models;

namespace PresentacionVentR.Controllers
{
    public class UsuarioController : Controller
    {
        private ApiUsuarioHelper api = new ApiUsuarioHelper();

        // GET: UsuarioController
        public ActionResult AgregarUsuarioView()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> ModificarUsuarioView(int idUsuario)
        {
            return View(await api.ObtenerUsuarioEspecifico(idUsuario));
        }

        public async Task<IActionResult> ListarUsuarioView()
        {
            var respuesta = await api.ListarUsuarios();
            return View(respuesta);

        }

        [HttpPost]
        public async Task<IActionResult> Registrar(Usuario usuario)
        {

            if (await api.RegistrarUsuario(usuario))
            {
                return View("ListarUsuarioView", await api.ListarUsuarios());
            }
            return View("Error", new ErrorViewModel { RequestId = "2" });
        }

        [HttpPost]
        public async Task<IActionResult> Modificar(Usuario usuario)
        {
            if (await api.ActualizarUsuario(usuario)) {
                return View("ListarUsuarioView", await api.ListarUsuarios()); 
            }
            return View("Error", new ErrorViewModel { RequestId = "1"});
        }


        public async Task<IActionResult> EliminarUsuario(int idUsuario)
        {

            if (await api.EliminarUsuario(idUsuario))
            {
                return View("ListarUsuarioView", await api.ListarUsuarios());
            }

            return View("Error", new ErrorViewModel { RequestId = "3" });


        }

    }
}

BackEndVentR/BackEndVentR/PresentacionVentR/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Administrativo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img  src="~/img/VentR_logo-01.svg" width="100" height="100"/> Inicio</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Proveedor" asp-action="listarProveedores">Proveedor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="ListarUsuarioView">Usuarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Producto" asp-action="ProductoProveedorView">Producto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PresentacionVentR - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>