Cliente2/Cliente2/Models/Producto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cliente2.Models
{
    public class Producto
    {

        public int id_producto { get; set; }
        public string nombre { get; set; }
        public float precio { get; set; }
        public string url_img { get; set; }
        public int cantidad { get; set; }
        public byte estado { get; set; }
        public string descripcion { get; set; }
        public int id_proveedor { get; set; }

        public Producto()
        {
        }

        public Producto(int id_produto, string nombre, float precio, string url_img, int cantidad, byte estado, string descripcion, int id_proveedor)
        {
            this.id_producto = id_produto;
            this.nombre = nombre;
            this.precio = precio;
            this.url_img = url_img;
            this.cantidad = cantidad;
            this.estado = estado;
            this.descripcion = descripcion;
            this.id_proveedor = id_proveedor;
        }


        public Producto(int id_produto, int id_proveedor, int cantidad)
        {
            this.id_producto = id_produto;

            this.cantidad = cantidad;
            this.id_proveedor = id_proveedor;
        }
    }
}

Cliente2/Cliente2/Controllers/ApiConsumoLlaveController.cs
using Cliente2.EnvioDato;
using Cliente2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Cliente2.Controllers
{
    public class ApiConsumoLlaveController : Controller
    {

        [HttpGet]
        public async Task<ActionResult> RecibirLlave()
        {
            ReciboDatoLlave dato = new ReciboDatoLlave();
            Llave respuesta = await dato.recibirLlave();

            return View(respuesta);
        }
    }
}

Cliente2/Cliente2/Controllers/ProductoController.cs
using Cliente2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cliente2.Controllers
{
    public class ProductoController : Controller
    {

        private ProductoData pd;

        // GET: Producto
        public ActionResult ObtenerLista()
        {
            pd = new ProductoData();
            ModelState.Clear();
            return View(pd.ObtenerProductos());
        }

        [HttpGet]
        public ActionResult Agregar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Agregar(Producto producto)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    pd = new ProductoData();
                    if (pd.Add(producto))
                    {
                        ViewBag.Mensagem = " ingresado con exito ";
                    }

                }
                return View();
            }
            catch (Exception)
            {
                return View("ObtenerLista");
            }
        }



        [HttpGet]
        public ActionResult ModificarProducto(int id_producto, int id_proveedor, int cantidad)
        {
            pd = new ProductoData();
            pd.ActualizarCantidad(new Producto(id_producto, id_proveedor, cantidad));

            return View("ObtenerLista", pd.ObtenerProductos());

        }



        public ActionResult Actualizar(int id)
        {
            pd = new ProductoData();
            return View(pd.ObtenerProductos().Find(t => t.id_producto == id));
        }
        [HttpPost]
        public ActionResult Actualizar(int id, Producto producto)
        {
            try
            {
                pd = new ProductoData();
                if (pd.Actualizar(producto))
                {
                    ViewBag.Mensagen = " Modificado con exito ";
                }
                return View(pd.ObtenerProductos().Find(t => t.id_producto == id));
            }
            catch (Exception)
            {
                return View("ObtenerLista");
            }
        }

        public ActionResult Eliminar(int id)
        {
            try
            {
                pd = new ProductoData();
                if (pd.Eliminar(id))
                {
                    ViewBag.Mensagem = "Eliminado con exito";
                }
                return RedirectToAction("ObtenerLista");
            }
            catch (Exception)
            {
                return View("ObtenerLista");
            }
        }

    }
}

Cliente2/Cliente2/Views/Producto/Actualizar.cshtml
@model Cliente2.Models.Producto


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Producto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.id_producto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_producto, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.id_producto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.url_img, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.url_img, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.url_img, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cantidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cantidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.estado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_proveedor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_proveedor, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.id_proveedor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10" style="color:lawngreen">
                @ViewBag.Mensagen
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "ObtenerLista")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Cliente2/Cliente2/Views/Producto/Agregar.cshtml
@model Cliente2.Models.Producto


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Producto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
                @Html.LabelFor(model => model.id_produto, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.id_produto, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.id_produto, "", new { @class = "text-danger" })
                </div>
            </div>*@
        <div class="form-group">
            @Html.LabelFor(model => model.id_proveedor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_proveedor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id_proveedor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.url_img, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.url_img, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.url_img, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cantidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cantidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.estado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10" style="color:lawngreen">
                @ViewBag.Mensagem
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "ObtenerLista")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Cliente2/Cliente2/Views/Producto/ObtenerLista.cshtml
@model IEnumerable<Cliente2.Models.Producto>

<p>
    @Html.ActionLink("Agregar Producto", "Agregar")
    <!--@Html.ActionLink("Generar Llave", "RecibirLlave", "ApiConsumoLlave")-->
</p>

<button id="ver" onclick="getLlave()">Ver Llave</button>

<button onclick="crearLlave()">Crear Llave</button>

<button onclick="sincronizar()">Sincronizar</button>

<button onclick="enviarProductos()">Enviar Productos</button>

<h3 id="llave"></h3>

<table class="table">
    <tr>
        @*<th>
                @Html.DisplayNameFor(model => model.id_produto)
            </th>*@
        <th>
            @Html.DisplayNameFor(model => model.id_proveedor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.precio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.url_img)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cantidad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.estado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.descripcion)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            @*<td>
                    @Html.DisplayFor(modelItem => item.id_produto)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.id_proveedor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.precio)
            </td>
            <td>
                <img src="@Html.DisplayFor(modelItem => item.url_img)" width="50" height="50" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cantidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.estado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.descripcion)
            </td>
            <td>
                @Html.ActionLink("Actualizar", "Actualizar", new { id = item.id_producto }) |
                @Html.ActionLink("Eliminar", "Eliminar", new { id = item.id_producto })
            </td>
        </tr>
    }

</table>
@section scripts{
    <script type="text/javascript">

        let llave = '';
        let mostrar = false;

        function getLlave() {
            if (!mostrar) {
                $.get('http://localhost:59292/api/Llave/3/llave').done(function (data) {
                    //console.log(data);
                    //data.atributo => para acceder al valor
                    if (data == undefined) {
                        $("#llave").text("Este proveedor no contiene una llave");
                    }
                    else {
                        $("#llave").text(data.codLlave);
                        llave = data.codLlave;
                    }

                    $("#ver").text("Ocultar llave");
                    mostrar = true;
                });
            }
            else {
                $("#llave").text("");
                $("#ver").text("Ver llave");
                mostrar = false;
            }
        }

        function crearLlave() {
            $.ajax({
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                },
                method: 'POST',
                url: 'http://localhost:59292/api/Llave',
                data: JSON.stringify({ idProveedor: 3 }),
                dataType: "json"
            })
                .done(() => alert("La creación de la llave fué exitosa"))
                .fail((e) => alert("error: " + e));
        }

        function sincronizar() {
            //Solamente es de cambiar el url del back end aqui, lo demas está bien
            let cantidad, producto_proveedor;
            let url = 'http://localhost:59292/api/Proveedor/3/' + llave + '/sincronizacion';

            $.get(url)
                .done((data) => {

                    //console.log(data);
                    // TODO mostrar el Json de los productos vendidos con su cantidad

                    data.forEach((producto) => {
                        cantidad = producto.cantidad;
                        producto_proveedor = producto.idProducto;
                        sincronizarProducto(3, producto_proveedor, cantidad);
                    });


                    alert("Sincronizado correctamente con VentR");
                })
                .fail((e) => alert("Error al sincronizar: " + e));
        }


        function sincronizarProducto(idProveedor, producto_proveedor, cantidad) {

            $.ajax({
                url: '/Producto/ModificarProducto',
                type: 'GET',
                data: {
                    "id_producto": parseInt(producto_proveedor),
                    "id_proveedor": parseInt(idProveedor),
                    "cantidad": parseInt(cantidad)
                },
                success: function (response) {
                    console.log(response);
                    if (response) {
                        alert('El producto fue sincronizado exitosamente.');
                    } else {
                        alert('No ha sido sincronizado');
                    }
                },
                error: function (error) {
                }
            });
        }


        function enviarProductos() {

            let url = 'http://localhost:59292/api/Proveedor/3/' + llave + '/recibirProductos';

            $.get('https://localhost:44358/api/ApiProducto')
                .done((data) => {

                    $.ajax({
                        url: url,
                        type: "POST",
                        data: JSON.stringify(data),
                        contentType: "application/json; charset=utf-8",
                        dataType: "json",
                        success: (res) => { alert("Exito " + res); }
                    });
                })
        }
    </script>
}